I think that the Random Forest Classifier will be best on the UNSCALED data.

I think the Random Forest Classifier will be best on the SCALED data 

In [3]:
# standard libraries
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
from pathlib import Path

# processing libraries
# from sklearn.model_selection import train_test_split # not needed
from sklearn.preprocessing import StandardScaler

# metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import roc_curve, auc

# models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier

In [4]:
# read path
train_df = pd.read_csv('Resources/2019loans.csv')
test_df = pd.read_csv('Resources/2020Q1loans.csv')

In [5]:
test_df.head()

Unnamed: 0  index  loan_amnt  int_rate  installment home_ownership  \
0       67991  67991    40000.0    0.0819       814.70       MORTGAGE   
1       25429  25429     6000.0    0.1524       208.70           RENT   
2       38496  38496     3600.0    0.1695       128.27           RENT   
3       19667  19667    20000.0    0.1524       478.33           RENT   
4       37505  37505     3600.0    0.1240       120.27           RENT   

   annual_inc verification_status loan_status pymnt_plan    dti  delinq_2yrs  \
0    140000.0        Not Verified    low_risk          n  19.75          0.0   
1     55000.0        Not Verified    low_risk          n  11.52          2.0   
2     42000.0        Not Verified    low_risk          n   6.74          0.0   
3    100000.0        Not Verified    low_risk          n  12.13          0.0   
4     50000.0        Not Verified    low_risk          n  16.08          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  total_acc  \
0             1.0      18.0      0.0     9471.0       45.0   
1             0.0       8.0      0.0     1280.0       12.0   
2             0.0       6.0      0.0     4757.0        6.0   
3             2.0       7.0      0.0    12731.0       21.0   
4             3.0       6.0      0.0    10413.0        6.0   

  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  \
0                   w   33249.95       33249.95      9740.00          9740.00   
1                   w       0.00           0.00      6185.59          6185.59   
2                   w       0.00           0.00      3603.73          3603.73   
3                   w   17624.06       17624.06      4766.37          4766.37   
4                   w       0.00           0.00      3602.48          3602.48   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0          6750.05        2989.95                 0.0         0.0   
1          6000.00         185.59                 0.0         0.0   
2          3600.00           3.73                 0.0         0.0   
3          2375.94        2390.43                 0.0         0.0   
4          3600.00           2.48                 0.0         0.0   

   collection_recovery_fee  last_pymnt_amnt  collections_12_mths_ex_med  \
0                      0.0           814.70                         0.0   
1                      0.0          5773.27                         0.0   
2                      0.0          3607.12                         0.0   
3                      0.0           478.33                         0.0   
4                      0.0          3604.96                         0.0   

   policy_code application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  \
0          1.0       Individual             0.0           0.0     377773.0   
1          1.0       Individual             0.0           0.0      23460.0   
2          1.0       Individual             0.0           0.0      19183.0   
3          1.0       Individual             0.0           0.0      43817.0   
4          1.0       Individual             0.0           0.0      32448.0   

   open_acc_6m  open_act_il  open_il_12m  open_il_24m  mths_since_rcnt_il  \
0          1.0          6.0          1.0          2.0                 9.0   
1          1.0          1.0          1.0          1.0                 6.0   
2          0.0          3.0          0.0          0.0                40.0   
3          1.0          2.0          1.0          3.0                11.0   
4          2.0          2.0          1.0          1.0                 9.0   

   total_bal_il  il_util  open_rv_12m  open_rv_24m  max_bal_bc  all_util  \
0       61443.0     51.0          1.0          1.0      3218.0      26.0   
1       22180.0     94.0          0.0          1.0       713.0      68.0   
2       14426.0     96.0          1.0          2.0      4757.0      83.0   
3       31086.0     86.0          3.0          3.0      5917.0      78.0   
4       22035.0     88.0          2.0        

In [6]:
train_df.head()

Unnamed: 0   index  loan_amnt  int_rate  installment home_ownership  \
0       57107   57107    13375.0    0.1797       483.34       MORTGAGE   
1      141451  141451    21000.0    0.1308       478.68       MORTGAGE   
2      321143  321143    20000.0    0.1240       448.95       MORTGAGE   
3       11778   11778     3000.0    0.1240       100.22           RENT   
4      169382  169382    30000.0    0.1612      1056.49       MORTGAGE   

   annual_inc verification_status loan_status pymnt_plan    dti  delinq_2yrs  \
0    223000.0        Not Verified    low_risk          n  29.99          0.0   
1    123000.0     Source Verified    low_risk          n  11.26          2.0   
2    197000.0     Source Verified    low_risk          n  11.28          0.0   
3     45000.0        Not Verified    low_risk          n  18.08          0.0   
4    133000.0     Source Verified    low_risk          n  27.77          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  total_acc  \
0             0.0      15.0      0.0    39728.0       38.0   
1             0.0      16.0      0.0     9585.0       20.0   
2             0.0      12.0      0.0    16708.0       36.0   
3             0.0      12.0      1.0     8809.0       19.0   
4             2.0      13.0      0.0    65420.0       51.0   

  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  \
0                   w   12804.66       12804.66       953.33           953.33   
1                   w   15152.97       15152.97     10037.02         10037.02   
2                   w   15724.23       15724.23      6971.52          6971.52   
3                   w    2930.77        2930.77        81.63            81.63   
4                   w   20778.03       20778.03     14763.99         14763.99   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0           570.34         382.99                 0.0         0.0   
1          5847.03        4189.99                 0.0         0.0   
2          4275.77        2695.75                 0.0         0.0   
3            69.23          12.40                 0.0         0.0   
4          9221.97        5542.02                 0.0         0.0   

   collection_recovery_fee  last_pymnt_amnt  collections_12_mths_ex_med  \
0                      0.0           483.34                         0.0   
1                      0.0           478.68                         0.0   
2                      0.0           448.95                         0.0   
3                      0.0            85.76                         1.0   
4                      0.0          1056.49                         0.0   

   policy_code application_type  acc_now_delinq  tot_coll_amt  tot_cur_bal  \
0          1.0       Individual             0.0           0.0     465790.0   
1          1.0       Individual             0.0           0.0      60769.0   
2          1.0       Individual             0.0           0.0     617946.0   
3          1.0       Individual             0.0         568.0      20761.0   
4          1.0       Individual             0.0           0.0     237839.0   

   open_acc_6m  open_act_il  open_il_12m  open_il_24m  mths_since_rcnt_il  \
0          2.0          7.0          3.0          7.0                 7.0   
1          0.0          2.0          0.0          1.0                17.0   
2          1.0          7.0          1.0          2.0                 5.0   
3          2.0          4.0          2.0          2.0                 8.0   
4          2.0          3.0          1.0          3.0                 5.0   

   total_bal_il  il_util  open_rv_12m  open_rv_24m  max_bal_bc  all_util  \
0       82290.0     70.0          1.0          1.0     24683.0      69.0   
1       18311.0     52.0          0.0          4.0      4311.0      50.0   
2       97335.0    108.0          0.0          0.0     11026.0      98.0   
3       11952.0     78.0          2.0          4.0      2409.0      49.0   
4       43636.0     74.0          1.0  

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Unnamed: 0                  12180 non-null  int64  
 1   index                       12180 non-null  int64  
 2   loan_amnt                   12180 non-null  float64
 3   int_rate                    12180 non-null  float64
 4   installment                 12180 non-null  float64
 5   home_ownership              12180 non-null  object 
 6   annual_inc                  12180 non-null  float64
 7   verification_status         12180 non-null  object 
 8   loan_status                 12180 non-null  object 
 9   pymnt_plan                  12180 non-null  object 
 10  dti                         12180 non-null  float64
 11  delinq_2yrs                 12180 non-null  float64
 12  inq_last_6mths              12180 non-null  float64
 13  open_acc                    121

In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Unnamed: 0                  4702 non-null   int64  
 1   index                       4702 non-null   int64  
 2   loan_amnt                   4702 non-null   float64
 3   int_rate                    4702 non-null   float64
 4   installment                 4702 non-null   float64
 5   home_ownership              4702 non-null   object 
 6   annual_inc                  4702 non-null   float64
 7   verification_status         4702 non-null   object 
 8   loan_status                 4702 non-null   object 
 9   pymnt_plan                  4702 non-null   object 
 10  dti                         4702 non-null   float64
 11  delinq_2yrs                 4702 non-null   float64
 12  inq_last_6mths              4702 non-null   float64
 13  open_acc                    4702 

In [9]:
len(train_df) / (len(train_df) + len(test_df))

0.7214784978083165

In [10]:
# look at target
train_df.loan_status.value_counts()

high_risk    6090
low_risk     6090
Name: loan_status, dtype: int64

In [11]:
# look at the target feature in training set
test_df.loan_status.value_counts()

high_risk    2351
low_risk     2351
Name: loan_status, dtype: int64

In [12]:
# Label encode the target
train_df["loan_status"] = [1 if x == "high_risk" else 0 for x in train_df.loan_status]
test_df["loan_status"] = [1 if x == "high_risk" else 0 for x in test_df.loan_status]

In [13]:

train_df.loan_status.value_counts()

0    6090
1    6090
Name: loan_status, dtype: int64

In [14]:
test_df.loan_status.value_counts()

0    2351
1    2351
Name: loan_status, dtype: int64

In [15]:
# viewing category data
category_df = train_df.select_dtypes(include='object')
category_df.head()

home_ownership verification_status pymnt_plan initial_list_status  \
0       MORTGAGE        Not Verified          n                   w   
1       MORTGAGE     Source Verified          n                   w   
2       MORTGAGE     Source Verified          n                   w   
3           RENT        Not Verified          n                   w   
4       MORTGAGE     Source Verified          n                   w   

  application_type hardship_flag debt_settlement_flag  
0       Individual             N                    N  
1       Individual             N                    N  
2       Individual             N                    N  
3       Individual             N                    N  
4       Individual             N                    N

In [16]:
for col in category_df.columns:
    print(category_df[col].value_counts())
    print()

MORTGAGE    5800
RENT        4944
OWN         1371
ANY           65
Name: home_ownership, dtype: int64

Not Verified       5301
Source Verified    4881
Verified           1998
Name: verification_status, dtype: int64

n    12180
Name: pymnt_plan, dtype: int64

w    11158
f     1022
Name: initial_list_status, dtype: int64

Individual    10400
Joint App      1780
Name: application_type, dtype: int64

N    11832
Y      348
Name: hardship_flag, dtype: int64

N    12175
Y        5
Name: debt_settlement_flag, dtype: int64



In [17]:
cat_df2 = test_df.select_dtypes(include='object')
for col in cat_df2.columns:
    print(cat_df2[col].value_counts())
    print()

MORTGAGE    2131
RENT        2033
OWN          533
ANY            5
Name: home_ownership, dtype: int64

Not Verified       2454
Source Verified    1715
Verified            533
Name: verification_status, dtype: int64

n    4702
Name: pymnt_plan, dtype: int64

w    4377
f     325
Name: initial_list_status, dtype: int64

Individual    4165
Joint App      537
Name: application_type, dtype: int64

N    4621
Y      81
Name: hardship_flag, dtype: int64

N    4702
Name: debt_settlement_flag, dtype: int64



In [18]:
# Converting category data to numeric
train_df_cat = pd.get_dummies(category_df)
test_df_cat = pd.get_dummies(cat_df2)

In [19]:
train_df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   home_ownership_ANY                   12180 non-null  uint8
 1   home_ownership_MORTGAGE              12180 non-null  uint8
 2   home_ownership_OWN                   12180 non-null  uint8
 3   home_ownership_RENT                  12180 non-null  uint8
 4   verification_status_Not Verified     12180 non-null  uint8
 5   verification_status_Source Verified  12180 non-null  uint8
 6   verification_status_Verified         12180 non-null  uint8
 7   pymnt_plan_n                         12180 non-null  uint8
 8   initial_list_status_f                12180 non-null  uint8
 9   initial_list_status_w                12180 non-null  uint8
 10  application_type_Individual          12180 non-null  uint8
 11  application_type_Joint App           12180 non-null  u

In [20]:
test_df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   home_ownership_ANY                   4702 non-null   uint8
 1   home_ownership_MORTGAGE              4702 non-null   uint8
 2   home_ownership_OWN                   4702 non-null   uint8
 3   home_ownership_RENT                  4702 non-null   uint8
 4   verification_status_Not Verified     4702 non-null   uint8
 5   verification_status_Source Verified  4702 non-null   uint8
 6   verification_status_Verified         4702 non-null   uint8
 7   pymnt_plan_n                         4702 non-null   uint8
 8   initial_list_status_f                4702 non-null   uint8
 9   initial_list_status_w                4702 non-null   uint8
 10  application_type_Individual          4702 non-null   uint8
 11  application_type_Joint App           4702 non-null   uin

In [21]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Unnamed: 0                  12180 non-null  int64  
 1   index                       12180 non-null  int64  
 2   loan_amnt                   12180 non-null  float64
 3   int_rate                    12180 non-null  float64
 4   installment                 12180 non-null  float64
 5   home_ownership              12180 non-null  object 
 6   annual_inc                  12180 non-null  float64
 7   verification_status         12180 non-null  object 
 8   loan_status                 12180 non-null  int64  
 9   pymnt_plan                  12180 non-null  object 
 10  dti                         12180 non-null  float64
 11  delinq_2yrs                 12180 non-null  float64
 12  inq_last_6mths              12180 non-null  float64
 13  open_acc                    121

In [22]:
num_train_df = train_df.select_dtypes(include=['float64', 'int64'])
train_df_real = pd.merge(num_train_df, train_df_cat, left_index=True, right_index=True)

train_df_real.head()

Unnamed: 0   index  loan_amnt  int_rate  installment  annual_inc  \
0       57107   57107    13375.0    0.1797       483.34    223000.0   
1      141451  141451    21000.0    0.1308       478.68    123000.0   
2      321143  321143    20000.0    0.1240       448.95    197000.0   
3       11778   11778     3000.0    0.1240       100.22     45000.0   
4      169382  169382    30000.0    0.1612      1056.49    133000.0   

   loan_status    dti  delinq_2yrs  inq_last_6mths  open_acc  pub_rec  \
0            0  29.99          0.0             0.0      15.0      0.0   
1            0  11.26          2.0             0.0      16.0      0.0   
2            0  11.28          0.0             0.0      12.0      0.0   
3            0  18.08          0.0             0.0      12.0      1.0   
4            0  27.77          0.0             2.0      13.0      0.0   

   revol_bal  total_acc  out_prncp  out_prncp_inv  total_pymnt  \
0    39728.0       38.0   12804.66       12804.66       953.33   
1     9585.0       20.0   15152.97       15152.97     10037.02   
2    16708.0       36.0   15724.23       15724.23      6971.52   
3     8809.0       19.0    2930.77        2930.77        81.63   
4    65420.0       51.0   20778.03       20778.03     14763.99   

   total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
0           953.33           570.34         382.99                 0.0   
1         10037.02          5847.03        4189.99                 0.0   
2          6971.52          4275.77        2695.75                 0.0   
3            81.63            69.23          12.40                 0.0   
4         14763.99          9221.97        5542.02                 0.0   

   recoveries  collection_recovery_fee  last_pymnt_amnt  \
0         0.0                      0.0           483.34   
1         0.0                      0.0           478.68   
2         0.0                      0.0           448.95   
3         0.0                      0.0            85.76   
4         0.0                      0.0          1056.49   

   collections_12_mths_ex_med  policy_code  acc_now_delinq  tot_coll_amt  \
0                         0.0          1.0             0.0           0.0   
1                         0.0          1.0             0.0           0.0   
2                         0.0          1.0             0.0           0.0   
3                         1.0          1.0             0.0         568.0   
4                         0.0          1.0             0.0           0.0   

   tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
0     465790.0          2.0          7.0          3.0          7.0   
1      60769.0          0.0          2.0          0.0          1.0   
2     617946.0          1.0          7.0          1.0          2.0   
3      20761.0          2.0          4.0          2.0          2.0   
4     237839.0          2.0          3.0          1.0          3.0   

   mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  open_rv_24m  \
0                 7.0       82290.0     70.0          1.0          1.0   
1                17.0       18311.0     52.0          0.0          4.0   
2                 5.0       97335.0    108.0          0.0          0.0   
3                 8.0       11952.0     78.0          2.0          4.0   
4                 5.0       43636.0     74.0          1.0          1.0   

   max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl  inq_last_12m  \
0     24683.0      69.0           60200.0     1.0         12.0           2.0   
1      4311.0      50.0           20900.0     1.0          0.0           1.0   
2     11026.0      98.0           25900.0     2.0          0.0           2.0   
3      2409.0      49.0           26600.0     4.0          4.0           2.0   
4     19804.0      74.0           88100.0     2.0         11.0           3.0   

   acc_open_past_24mths  avg_cur_bal  bc_open_to_buy  bc_util  \
0                   9.0      31053.0          7317.0     77.1   
1     

In [23]:
num_train_df.head()

Unnamed: 0   index  loan_amnt  int_rate  installment  annual_inc  \
0       57107   57107    13375.0    0.1797       483.34    223000.0   
1      141451  141451    21000.0    0.1308       478.68    123000.0   
2      321143  321143    20000.0    0.1240       448.95    197000.0   
3       11778   11778     3000.0    0.1240       100.22     45000.0   
4      169382  169382    30000.0    0.1612      1056.49    133000.0   

   loan_status    dti  delinq_2yrs  inq_last_6mths  open_acc  pub_rec  \
0            0  29.99          0.0             0.0      15.0      0.0   
1            0  11.26          2.0             0.0      16.0      0.0   
2            0  11.28          0.0             0.0      12.0      0.0   
3            0  18.08          0.0             0.0      12.0      1.0   
4            0  27.77          0.0             2.0      13.0      0.0   

   revol_bal  total_acc  out_prncp  out_prncp_inv  total_pymnt  \
0    39728.0       38.0   12804.66       12804.66       953.33   
1     9585.0       20.0   15152.97       15152.97     10037.02   
2    16708.0       36.0   15724.23       15724.23      6971.52   
3     8809.0       19.0    2930.77        2930.77        81.63   
4    65420.0       51.0   20778.03       20778.03     14763.99   

   total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
0           953.33           570.34         382.99                 0.0   
1         10037.02          5847.03        4189.99                 0.0   
2          6971.52          4275.77        2695.75                 0.0   
3            81.63            69.23          12.40                 0.0   
4         14763.99          9221.97        5542.02                 0.0   

   recoveries  collection_recovery_fee  last_pymnt_amnt  \
0         0.0                      0.0           483.34   
1         0.0                      0.0           478.68   
2         0.0                      0.0           448.95   
3         0.0                      0.0            85.76   
4         0.0                      0.0          1056.49   

   collections_12_mths_ex_med  policy_code  acc_now_delinq  tot_coll_amt  \
0                         0.0          1.0             0.0           0.0   
1                         0.0          1.0             0.0           0.0   
2                         0.0          1.0             0.0           0.0   
3                         1.0          1.0             0.0         568.0   
4                         0.0          1.0             0.0           0.0   

   tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
0     465790.0          2.0          7.0          3.0          7.0   
1      60769.0          0.0          2.0          0.0          1.0   
2     617946.0          1.0          7.0          1.0          2.0   
3      20761.0          2.0          4.0          2.0          2.0   
4     237839.0          2.0          3.0          1.0          3.0   

   mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  open_rv_24m  \
0                 7.0       82290.0     70.0          1.0          1.0   
1                17.0       18311.0     52.0          0.0          4.0   
2                 5.0       97335.0    108.0          0.0          0.0   
3                 8.0       11952.0     78.0          2.0          4.0   
4                 5.0       43636.0     74.0          1.0          1.0   

   max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl  inq_last_12m  \
0     24683.0      69.0           60200.0     1.0         12.0           2.0   
1      4311.0      50.0           20900.0     1.0          0.0           1.0   
2     11026.0      98.0           25900.0     2.0          0.0           2.0   
3      2409.0      49.0           26600.0     4.0          4.0           2.0   
4     19804.0      74.0           88100.0     2.0         11.0           3.0   

   acc_open_past_24mths  avg_cur_bal  bc_open_to_buy  bc_util  \
0                   9.0      31053.0          7317.0     77.1   
1     

In [24]:
# merging all numeric data
num_test_df = test_df.select_dtypes(include=['float64', 'int64'])
test_df_real = pd.merge(num_test_df, test_df_cat, left_index=True, right_index=True)

test_df_real.head()

Unnamed: 0  index  loan_amnt  int_rate  installment  annual_inc  \
0       67991  67991    40000.0    0.0819       814.70    140000.0   
1       25429  25429     6000.0    0.1524       208.70     55000.0   
2       38496  38496     3600.0    0.1695       128.27     42000.0   
3       19667  19667    20000.0    0.1524       478.33    100000.0   
4       37505  37505     3600.0    0.1240       120.27     50000.0   

   loan_status    dti  delinq_2yrs  inq_last_6mths  open_acc  pub_rec  \
0            0  19.75          0.0             1.0      18.0      0.0   
1            0  11.52          2.0             0.0       8.0      0.0   
2            0   6.74          0.0             0.0       6.0      0.0   
3            0  12.13          0.0             2.0       7.0      0.0   
4            0  16.08          0.0             3.0       6.0      0.0   

   revol_bal  total_acc  out_prncp  out_prncp_inv  total_pymnt  \
0     9471.0       45.0   33249.95       33249.95      9740.00   
1     1280.0       12.0       0.00           0.00      6185.59   
2     4757.0        6.0       0.00           0.00      3603.73   
3    12731.0       21.0   17624.06       17624.06      4766.37   
4    10413.0        6.0       0.00           0.00      3602.48   

   total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
0          9740.00          6750.05        2989.95                 0.0   
1          6185.59          6000.00         185.59                 0.0   
2          3603.73          3600.00           3.73                 0.0   
3          4766.37          2375.94        2390.43                 0.0   
4          3602.48          3600.00           2.48                 0.0   

   recoveries  collection_recovery_fee  last_pymnt_amnt  \
0         0.0                      0.0           814.70   
1         0.0                      0.0          5773.27   
2         0.0                      0.0          3607.12   
3         0.0                      0.0           478.33   
4         0.0                      0.0          3604.96   

   collections_12_mths_ex_med  policy_code  acc_now_delinq  tot_coll_amt  \
0                         0.0          1.0             0.0           0.0   
1                         0.0          1.0             0.0           0.0   
2                         0.0          1.0             0.0           0.0   
3                         0.0          1.0             0.0           0.0   
4                         0.0          1.0             0.0           0.0   

   tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
0     377773.0          1.0          6.0          1.0          2.0   
1      23460.0          1.0          1.0          1.0          1.0   
2      19183.0          0.0          3.0          0.0          0.0   
3      43817.0          1.0          2.0          1.0          3.0   
4      32448.0          2.0          2.0          1.0          1.0   

   mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  open_rv_24m  \
0                 9.0       61443.0     51.0          1.0          1.0   
1                 6.0       22180.0     94.0          0.0          1.0   
2                40.0       14426.0     96.0          1.0          2.0   
3                11.0       31086.0     86.0          3.0          3.0   
4                 9.0       22035.0     88.0          2.0          2.0   

   max_bal_bc  all_util  total_rev_hi_lim  inq_fi  total_cu_tl  inq_last_12m  \
0      3218.0      26.0           86500.0     0.0          2.0           1.0   
1       713.0      68.0           11000.0     1.0          1.0           3.0   
2      4757.0      83.0            8100.0     0.0          0.0           2.0   
3      5917.0      78.0           20500.0     0.0          3.0           3.0   
4      5985.0      71.0           21000.0     3.0          1.0          14.0   

   acc_open_past_24mths  avg_cur_bal  bc_open_to_buy  bc_util  \
0                   3.0      20987.0         65129.0     12.7   
1           

In [25]:
# add missing dummy variables to testing set
for col in train_df_real.columns:
    if col not in test_df_real.columns:
        print(col)
        test_df_real[col] = 0

debt_settlement_flag_Y


In [26]:
train_df_real.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 95 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Unnamed: 0                           12180 non-null  int64  
 1   index                                12180 non-null  int64  
 2   loan_amnt                            12180 non-null  float64
 3   int_rate                             12180 non-null  float64
 4   installment                          12180 non-null  float64
 5   annual_inc                           12180 non-null  float64
 6   loan_status                          12180 non-null  int64  
 7   dti                                  12180 non-null  float64
 8   delinq_2yrs                          12180 non-null  float64
 9   inq_last_6mths                       12180 non-null  float64
 10  open_acc                             12180 non-null  float64
 11  pub_rec                     

In [27]:
np.sqrt(len(train_df_real))

110.36303729057116

In [28]:
test_df_real.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 95 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Unnamed: 0                           4702 non-null   int64  
 1   index                                4702 non-null   int64  
 2   loan_amnt                            4702 non-null   float64
 3   int_rate                             4702 non-null   float64
 4   installment                          4702 non-null   float64
 5   annual_inc                           4702 non-null   float64
 6   loan_status                          4702 non-null   int64  
 7   dti                                  4702 non-null   float64
 8   delinq_2yrs                          4702 non-null   float64
 9   inq_last_6mths                       4702 non-null   float64
 10  open_acc                             4702 non-null   float64
 11  pub_rec                       

In [29]:
# Dropping Unnamed, index, pymnt_plan_n columns
drop_columns = ['Unnamed: 0', 'index', "pymnt_plan_n"]

train_df_real.drop(drop_columns, axis=1, inplace=True)
test_df_real.drop(drop_columns, axis=1, inplace=True)

In [30]:
X_train = train_df_real.drop("loan_status", axis=1)
y_train = train_df_real.loan_status

X_test = test_df_real.drop("loan_status", axis=1)
y_test = test_df_real.loan_status

In [31]:
np.sqrt(len(X_train))

110.36303729057116

In [32]:
X_train.columns

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_in

In [33]:
X_test.columns

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_in

# Data Models

In [34]:
# Train the Logistic Regression model on the unscaled data and print score
lr = LogisticRegression()
lr = lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

print(f'Training Score: {lr.score(X_train, y_train)}')
print(f'Testing Score: {lr.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 0.6498357963875205
Testing Score: 0.5163760102084219

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.51      0.73      0.60      2351
           1       0.53      0.30      0.39      2351

    accuracy                           0.52      4702
   macro avg       0.52      0.52      0.49      4702
weighted avg       0.52      0.52      0.49      4702


CONFUSION MATRIX:
[[1715  636]
 [1638  713]]


C:\Users\Thi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
?Train a random Forest Classifier model and print the score
rf = RandomForestClassifier(random_state=12, n_estimators=25)
rf = rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print(f'Training Score: {rf.score(X_train, y_train)}')
print(f'Testing Score: {rf.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Object `Train a random Forest Classifier model and print the score` not found.
Training Score: 0.9990968801313629
Testing Score: 0.6125053168864313

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.66      0.46      0.54      2351
           1       0.59      0.76      0.66      2351

    accuracy                           0.61      4702
   macro avg       0.62      0.61      0.60      4702
weighted avg       0.62      0.61      0.60      4702


CONFUSION MATRIX:
[[1091 1260]
 [ 562 1789]]


# Scale

In [36]:
# Scale the data
scaler = StandardScaler()
# Train the scaler with the training data
scaler = scaler.fit(X_train)
# Transform the dataset with scaler
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [37]:
# Train the Logistic Regression model on the scaled data and print score
lr = LogisticRegression()
lr = lr.fit(X_train_scaled, y_train)

y_pred = lr.predict(X_test_scaled)

print(f'Training Score: {lr.score(X_train_scaled, y_train)}')
print(f'Testing Score: {lr.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 0.7078817733990148
Testing Score: 0.767333049766057

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.76      0.77      0.77      2351
           1       0.77      0.76      0.77      2351

    accuracy                           0.77      4702
   macro avg       0.77      0.77      0.77      4702
weighted avg       0.77      0.77      0.77      4702


CONFUSION MATRIX:
[[1819  532]
 [ 562 1789]]


C:\Users\Thi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [38]:
# Train Random Forest Classifier model on scaled data
rf = RandomForestClassifier(random_state=32, n_estimators=25)
rf = rf.fit(X_train_scaled, y_train)

y_pred = rf.predict(X_test_scaled)

print(f'Training Score: {rf.score(X_train_scaled, y_train)}')
print(f'Testing Score: {rf.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 0.9989326765188834
Testing Score: 0.6269672479795831

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.69      0.47      0.56      2351
           1       0.60      0.79      0.68      2351

    accuracy                           0.63      4702
   macro avg       0.64      0.63      0.62      4702
weighted avg       0.64      0.63      0.62      4702


CONFUSION MATRIX:
[[1101 1250]
 [ 504 1847]]


# Unscaled Data

In [39]:
dt = DecisionTreeClassifier(random_state=12)
dt = dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

print(f'Training Score: {dt.score(X_train, y_train)}')
print(f'Testing Score: {dt.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 1.0
Testing Score: 0.5344534240748617

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.55      0.41      0.47      2351
           1       0.53      0.65      0.58      2351

    accuracy                           0.53      4702
   macro avg       0.54      0.53      0.53      4702
weighted avg       0.54      0.53      0.53      4702


CONFUSION MATRIX:
[[ 974 1377]
 [ 812 1539]]


In [40]:
etc = ExtraTreesClassifier(random_state=12, n_estimators=25)
etc = etc.fit(X_train, y_train)

y_pred = etc.predict(X_test)

print(f'Training Score: {etc.score(X_train, y_train)}')
print(f'Testing Score: {etc.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 1.0
Testing Score: 0.5625265844321565

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.57      0.52      0.54      2351
           1       0.56      0.61      0.58      2351

    accuracy                           0.56      4702
   macro avg       0.56      0.56      0.56      4702
weighted avg       0.56      0.56      0.56      4702


CONFUSION MATRIX:
[[1216 1135]
 [ 922 1429]]


In [41]:
ada = AdaBoostClassifier(random_state=12, n_estimators=25)
ada = ada.fit(X_train, y_train)

y_pred = ada.predict(X_test)

print(f'Training Score: {ada.score(X_train, y_train)}')
print(f'Testing Score: {ada.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 0.7504926108374385
Testing Score: 0.7165036154827733

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.74      0.67      0.70      2351
           1       0.70      0.76      0.73      2351

    accuracy                           0.72      4702
   macro avg       0.72      0.72      0.72      4702
weighted avg       0.72      0.72      0.72      4702


CONFUSION MATRIX:
[[1579  772]
 [ 561 1790]]


In [42]:
from xgboost import XGBClassifier

In [43]:
xgb = XGBClassifier(random_state=12, n_estimators=25)
xgb = xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print(f'Training Score: {xgb.score(X_train, y_train)}')
print(f'Testing Score: {xgb.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


C:\Users\Thi\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:34:20] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Score: 0.8624794745484401
Testing Score: 0.5772011909825606

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.59      0.52      0.55      2351
           1       0.57      0.64      0.60      2351

    accuracy                           0.58      4702
   macro avg       0.58      0.58      0.58      4702
weighted avg       0.58      0.58      0.58      4702


CONFUSION MATRIX:
[[1211 1140]
 [ 848 1503]]


In [54]:
from lightgbm import LGBMClassifier

In [55]:
lgb = LGBMClassifier(random_state=12, n_estimators=25)
lgb = lgb.fit(X_train, y_train)

y_pred = lgb.predict(X_test)

print(f'Training Score: {lgb.score(X_train, y_train)}')
print(f'Testing Score: {lgb.score(X_test, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 0.8175697865353038
Testing Score: 0.5691195236069757

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.58      0.50      0.54      2351
           1       0.56      0.64      0.60      2351

    accuracy                           0.57      4702
   macro avg       0.57      0.57      0.57      4702
weighted avg       0.57      0.57      0.57      4702


CONFUSION MATRIX:
[[1177 1174]
 [ 852 1499]]


# Scaled

In [57]:
dt = DecisionTreeClassifier(random_state=32)
dt = dt.fit(X_train_scaled, y_train)

y_pred = dt.predict(X_test_scaled)

print(f'Training Score: {dt.score(X_train_scaled, y_train)}')
print(f'Testing Score: {dt.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 1.0
Testing Score: 0.5455125478519779

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.56      0.41      0.47      2351
           1       0.54      0.68      0.60      2351

    accuracy                           0.55      4702
   macro avg       0.55      0.55      0.54      4702
weighted avg       0.55      0.55      0.54      4702


CONFUSION MATRIX:
[[ 958 1393]
 [ 744 1607]]


In [58]:
etc = ExtraTreesClassifier(random_state=32, n_estimators=25)
etc = etc.fit(X_train_scaled, y_train)

y_pred = etc.predict(X_test_scaled)

print(f'Training Score: {etc.score(X_train_scaled, y_train)}')
print(f'Testing Score: {etc.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 1.0
Testing Score: 0.5710336027222459

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.58      0.52      0.55      2351
           1       0.56      0.62      0.59      2351

    accuracy                           0.57      4702
   macro avg       0.57      0.57      0.57      4702
weighted avg       0.57      0.57      0.57      4702


CONFUSION MATRIX:
[[1223 1128]
 [ 889 1462]]


In [59]:
ada = AdaBoostClassifier(random_state=32, n_estimators=25)
ada = ada.fit(X_train_scaled, y_train)

y_pred = ada.predict(X_test_scaled)

print(f'Training Score: {ada.score(X_train_scaled, y_train)}')
print(f'Testing Score: {ada.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


Training Score: 0.7504926108374385
Testing Score: 0.7165036154827733

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.74      0.67      0.70      2351
           1       0.70      0.76      0.73      2351

    accuracy                           0.72      4702
   macro avg       0.72      0.72      0.72      4702
weighted avg       0.72      0.72      0.72      4702


CONFUSION MATRIX:
[[1579  772]
 [ 561 1790]]


In [60]:
xgb = XGBClassifier(random_state=32, n_estimators=25)
xgb = xgb.fit(X_train_scaled, y_train)

y_pred = xgb.predict(X_test_scaled)

print(f'Training Score: {xgb.score(X_train_scaled, y_train)}')
print(f'Testing Score: {xgb.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))


C:\Users\Thi\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:41:22] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Score: 0.8624794745484401
Testing Score: 0.5772011909825606

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.59      0.52      0.55      2351
           1       0.57      0.64      0.60      2351

    accuracy                           0.58      4702
   macro avg       0.58      0.58      0.58      4702
weighted avg       0.58      0.58      0.58      4702


CONFUSION MATRIX:
[[1211 1140]
 [ 848 1503]]


In [61]:
lgb = LGBMClassifier(random_state=32, n_estimators=25)
lgb = lgb.fit(X_train_scaled, y_train)

y_pred = lgb.predict(X_test_scaled)

print(f'Training Score: {lgb.score(X_train_scaled, y_train)}')
print(f'Testing Score: {lgb.score(X_test_scaled, y_test)}')
print()
print("CLASSIFICATION REPORT:")
print(classification_report(y_test, y_pred))
print()
print("CONFUSION MATRIX:")
print(confusion_matrix(y_test, y_pred))



Training Score: 0.8164203612479475
Testing Score: 0.6463207145895363

CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           0       0.70      0.51      0.59      2351
           1       0.61      0.78      0.69      2351

    accuracy                           0.65      4702
   macro avg       0.66      0.65      0.64      4702
weighted avg       0.66      0.65      0.64      4702


CONFUSION MATRIX:
[[1195 1156]
 [ 507 1844]]


We find that Ada boost mdodel performs well on both the Unscaled and Scaled data sets. It's the best performing model besides the Logistic Regression model on the Scaled data.